# Generated by Django 3.1.5 on 2021-01-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210117_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
