# Generated by Django 3.1.5 on 2021-01-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210124_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
