# Generated by Django 3.1.6 on 2021-02-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210222_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to='avatar/'),
        ),
    ]
