# Generated by Django 3.1.6 on 2021-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210222_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='/static/images/def_avatar.png', null=True, upload_to='avatar/'),
        ),
    ]
